# Generated by Django 4.1.7 on 2023-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_task_author_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='label',
                to='labels.label',
                verbose_name='Label'
            ),
        ),
    ]
