# Generated by Django 4.1.7 on 2023-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_remove_task_tag_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(
                related_name='label',
                to='labels.label',
                verbose_name='Label'
            ),
        ),
    ]
