# Generated by Django 4.1.7 on 2023-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_creation_date'),
        ('tasks', '0006_alter_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(
                blank=True,
                related_name='label',
                to='labels.label',
                verbose_name='Labels'
            ),
        ),
    ]
