# Generated by Django 4.1.7 on 2023-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=100,
                    unique=True,
                    verbose_name='Name'
                )),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Label',
            },
        ),
    ]
